"""remove direction from transaction

Revision ID: 1054773ec759
Revises: 95fb82112965
Create Date: 2026-05-20 09:59:45.496273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1054773ec759"
down_revision: Union[str, Sequence[str], None] = "95fb82112965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "direction")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "transactions",
        sa.Column(
            "direction",
            postgresql.ENUM("incoming", "outgoing", name="transactiondirection"),
            nullable=True,
        ),
    )
