"""make card_id name recipient_account_number non-nullable

Revision ID: 180087c68080
Revises: 50ad3589ae25
Create Date: 2026-04-23 12:04:32.745883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180087c68080'
down_revision: Union[str, Sequence[str], None] = '50ad3589ae25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_templates', sa.Column('type', sa.Enum('reccuring', 'single', name='transactiontype'), nullable=False))
    op.alter_column('transaction_templates', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_templates', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('transaction_templates', 'recipient_account_number',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_templates', 'recipient_account_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('transaction_templates', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('transaction_templates', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transaction_templates', 'type')
    # ### end Alembic commands ###
