"""add is_deleted to users

Revision ID: 2db3ea3cf09f
Revises: eb10fe34356e
Create Date: 2026-04-15 11:20:48.037675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db3ea3cf09f'
down_revision: Union[str, Sequence[str], None] = 'eb10fe34356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false())
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
