"""Add start_date u recurring_transaction

Revision ID: 47b33ce1f79f
Revises: b7d9c2a4f1e8
Create Date: 2026-04-23 14:17:15.748171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47b33ce1f79f"
down_revision: Union[str, Sequence[str], None] = "b7d9c2a4f1e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recurring_transactions", sa.Column("start_date", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recurring_transactions", "start_date")
    # ### end Alembic commands ###
