"""Add recipient_account_number and update transaction_templates

Revision ID: 4ed3aac56553
Revises: b7d9c2a4f1e8
Create Date: 2026-04-22 14:02:25.621276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed3aac56553'
down_revision: Union[str, Sequence[str], None] = 'b7d9c2a4f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_templates', sa.Column('recipient_account_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_templates', 'recipient_account_number')
    # ### end Alembic commands ###
