"""Add soft delete flag to transaction_templates

Revision ID: 50ad3589ae25
Revises: 4ed3aac56553
Create Date: 2026-04-22 14:37:26.140492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50ad3589ae25"
down_revision: Union[str, Sequence[str], None] = "4ed3aac56553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_templates", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_templates", "is_deleted")
    # ### end Alembic commands ###
