"""add start_date to recurring_transactions

Revision ID: be9a04d184d0
Revises: 08c75ee0e9d6
Create Date: 2026-04-28 14:20:17.159153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9a04d184d0'
down_revision: Union[str, Sequence[str], None] = '08c75ee0e9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'start_date')
    # ### end Alembic commands ###
